#pragma once

// Generated by tinyml/export_centroid_header.py.
// Features: voltage, current, temperature, power

const int EDGE_SENTINEL_CLASS_COUNT = 6;
const int EDGE_SENTINEL_FEATURE_COUNT = 4;

const char* EDGE_SENTINEL_LABELS[] = {"current_deviation", "normal", "open_circuit", "partial_shading", "sensor_failure", "temperature_anomaly"};

const float EDGE_SENTINEL_CENTROIDS[6][4] = {
  {11.800824f, 0.914671f, 33.057609f, 10.788254f},
  {12.004753f, 0.847791f, 30.984257f, 10.177942f},
  {12.403101f, 0.019991f, 31.021808f, 0.247850f},
  {10.414083f, 0.280096f, 31.999926f, 2.916846f},
  {3.815052f, -0.040741f, -35.463467f, -0.273428f},
  {11.697903f, 0.757217f, 47.864277f, 8.858830f}
};
