"""Export the centroid JSON model to an ESP32-friendly C header."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MODEL = ROOT / "tinyml" / "centroid_model.json"
OUTPUT = ROOT / "tinyml" / "edge_sentinel_centroid_model.h"


def c_array(values: list[float]) -> str:
    return ", ".join(f"{value:.6f}f" for value in values)


def main() -> None:
    if not MODEL.exists():
        raise SystemExit("missing model: run python -m ml.train first")
    model = json.loads(MODEL.read_text(encoding="utf-8"))
    features = model["features"]
    centroids = model["centroids"]
    labels = sorted(centroids)
    rows = [c_array([centroids[label][feature] for feature in features]) for label in labels]
    label_lines = ", ".join(f'"{label}"' for label in labels)
    centroid_lines = ",\n  ".join("{" + row + "}" for row in rows)

    text = f"""#pragma once

// Generated by tinyml/export_centroid_header.py.
// Features: {", ".join(features)}

const int EDGE_SENTINEL_CLASS_COUNT = {len(labels)};
const int EDGE_SENTINEL_FEATURE_COUNT = {len(features)};

const char* EDGE_SENTINEL_LABELS[] = {{{label_lines}}};

const float EDGE_SENTINEL_CENTROIDS[{len(labels)}][{len(features)}] = {{
  {centroid_lines}
}};
"""
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"generated {OUTPUT}")


if __name__ == "__main__":
    main()
